
export const ADD_BROADCAST_MESSAGES = 'ADD_BROADCAST_MESSAGES';
export const ADD_BROADCAST_MESSAGES_SUCCESS = 'ADD_BROADCAST_MESSAGES_SUCCESS';
export const ADD_BROADCAST_MESSAGES_FAILURE = 'ADD_BROADCAST_MESSAGES_FAILURE';



export const RESTORE_COMPANY = 'RESTORE_COMPANY';


export const AUTO_COMPLETE_DROPDOWN = 'AUTO_COMPLETE_DROPDOWN'
export const GET_TASK_GROUPL = 'GET_TASK_GROUPL'
export const GET_TASK_GROUPL_SUCCESS = 'GET_TASK_GROUPL_SUCCESS'
export const GET_TASK_GROUPL_FAILURE = 'GET_TASK_GROUPL_FAILURE'
