export const RAISE_NEW_TICKET = 'RAISE_NEW_TICKET';
export const RAISE_NEW_TICKET_SUCCESS = 'RAISE_NEW_TICKET_SUCCESS';
export const RAISE_NEW_TICKET_FAILURE = 'RAISE_NEW_TICKET_FAILURE';

export const GET_TICKETS = 'GET_TICKETS';
export const GET_TICKETS_SUCCESS = 'GET_TICKETS_SUCCESS';
export const GET_TICKETS_FAILURE = 'GET_TICKETS_FAILURE';

export const GET_TICKET_TAGS = 'GET_TICKET_TAGS';
export const GET_TICKET_TAGS_SUCCESS = 'GET_TICKET_TAGS_SUCCESS';
export const GET_TICKET_TAGS_FAILURE = 'GET_TICKET_TAGS_FAILURE';

export const ADD_TICKET_EVENT = 'ADD_TICKET_EVENT';
export const ADD_TICKET_EVENT_SUCCESS = 'ADD_TICKET_EVENT_SUCCESS';
export const ADD_TICKET_EVENT_FAILURE = 'ADD_TICKET_EVENT_FAILURE';

export const GET_TICKET_EVENTS = 'GET_TICKETS_EVENT';
export const GET_TICKET_EVENTS_SUCCESS = 'GET_TICKETS_EVENT_SUCCESS';
export const GET_TICKET_EVENTS_FAILURE = 'GET_TICKETS_EVENT_FAILURE';

export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_FAILURE = 'GET_EMPLOYEES_FAILURE';

export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS';
export const ADD_EMPLOYEE_FAILURE = 'ADD_EMPLOYEE_FAILURE';


