
export const image = {
    render: require('./brand/8x render.png'),
    cup: require('./brand/cupimage.png'),
    blue: require('./brand/image 1.jpg'),
    white: require('./brand/image 2.jpg'),
    parking:require('./brand/parking.png'),
    QuantaGataLogo:require('./brand/QuantaGateLogo.jpg'),
    QuantaLogo:require('./brand/QuantaLogo.jpg'),
    image1:require('./brand/main image.png'),
    QrcodeMachine:require('./brand/QrcodeMachine.png'),
    Feature:require('./brand/feature.png'),
    Security:require('./brand/security.png'),
    Benefits:require('./brand/benefits.png'),
    EaseOfUse:require('./brand/Ease of use.png'),
    Rev:require('./brand/revolution image.png'),
    TMS_1:require('./brand/TMS_1.png'),
    TMS_2:require('./brand/TMS_2.png'),
    TMS_3:require('./brand/TMS_3.png'),
    TMS_4:require('./brand/TMS_4.png'),
    TMS_5:require('./brand/TMS_5.png'),
    TMS_6:require('./brand/TMS_6.png'),
    TMS_7:require('./brand/TMS_7.png'),
    TMS_8:require('./brand/TMS_8.png'),
    TMS_Logo:require('./brand/TMS_Logo.png')
}