export interface TaskStateProp {
    taskGroups: any
    tasks: any
    taskNumOfPages: any,
    taskCurrentPages: number,
    selectedTask: any,
    addTaskEvents: any,
    taskEventHistories: any,
    subTasks: any,
    taskEvents: any,
    selectedTaskStatus:any,
    taskEventsNumOfPages: any,
    taskEventsCurrentPages: number,
    referencesTasks: any,
    referencesTasksNumOfPages: any,
    referencesTasksCurrentPages: number,
    selectedTaskCode:any,
    taskUsers: any,
    eventsMessage:any,
    selectedMicroModal:boolean ,
    refreshTaskEvents: boolean,
    refreshEventMessage:boolean,
    refreshEventsMessage:boolean,
    taskEventAttachments: any,
    addVoiceRecord:any,
    taskEventAttachmentsCurrentPage: number,
    selectedTabPositions: any,
    taskDetails: any,
    subTaskGroups: any,
    eventAttachmentsMessageNumOfPages:any,
    eventAttachmentsMessageCurrentPages:any,
    assignedTask: any,
    taskParams: any,
    assignedDepartment:any,
    assignedDesignation:any,
    assignedEmployee:any,
    createdDepartment:any,
    createdDesignation:any,
    createdEmployee:any,
    breakDownTimeLine:any,
    addCompanyLabel:any,
    selectedTaskId:any,
    selectedReferenceDetails:any,
    addNormalMessage:any,
    addAttachmentsMessage:any,
    eventAttachmentsMessage:any,
    selectedCodeId:any
    
}
