export const GET_BROADCAST_MESSAGES = 'GET_BROADCAST_MESSAGES';
export const GET_BROADCAST_MESSAGES_SUCCESS = 'GET_BROADCAST_MESSAGES_SUCCESS';
export const GET_BROADCAST_MESSAGES_FAILURE = 'GET_BROADCAST_MESSAGES_FAILURE';