export const icons = {
  google: require('./Google/icon.png'),
  minus: require('./Minus/icon.png'),
  plus: require('./Plus/icon.png'),
  close: require('./Close/icon.png'),
  downArrow: require('./Downarrow/icon.png'),
  downArrowOutline: require('./DownarrowOutline/icon.png'),
  search: require('./Search/icon.png'),
  addFill: require('./AddFill/icon.png'),
  addFillRounded: require('./AddFillRounded/icon.png'),
  addFillSquare: require('./AddFillSquare/iconWhitePlus.png'),
  addOutline: require('./AddOutline/icon@3x.png'),
  navigationArrow: require('./NavigationArrow/icon.png'),
  arrowRight: require('./ArrowRight/icon.png'),
  calenderList: require('./CalenderList/icon.png'),
  backButton: require('./BackButton/icon.png'),
  quantaTms: require('./QuantaTms/icon.png'),
  booking: require('./Booking/icon.png'),
  bookingFill: require('./BookingFill/icon.png'),
  brandFill: require('./BrandFill/icon.png'),
  briefCase: require('./BriefCase/icon.png'),
  calender: require('./Calender/icon.png'),
  calenderBlack: require('./CalenderBlack/icon.png'),
  calenderCross: require('./CalenderCross/icon.png'),
  calenderDate: require('./CalenderDate/icon.png'),
  calenderFill: require('./CalenderFill/icon.png'),
  calenderLine: require('./CalenderLine/icon.png'),
  calenderTick: require('./CalenderTick/icon.png'),
  calenderTime: require('./CalenderTime/icon.png'),
  call: require('./Call/icon.png'),
  cart: require('./Cart/icon.png'),
  locationFill: require('./LocationFill/icon.png'),
  chatMiddle: require('./ChatMiddle/icon.png'),
  chatSmall: require('./ChatSmall/icon.png'),
  clock: require('./Clock/icon.png'),
  closeBtn: require('./CloseBtn/icon.png'),
  closeFill: require('./CloseFill/icon.png'),
  cross: require('./Cross/icon.png'),
  delete: require('./Delete/icon.png'),
  deleteCurve: require('./DeleteCurve/icon.png'),
  deleteLine: require('./DeleteCurve/icon.png'),
  doubleTick: require('./DoubleTick/icon.png'),
  dropDown: require('./Dropdown/icon.png'),
  edit: require('./Edit/icon.png'),
  eye: require('./Eye/icon.png'),
  faceBook: require('./Facebook/icon.png'),
  feed: require('./Feed/icon.png'),
  greenProfile: require('./GreenProfile/icon.png'),
  home: require('./Home/icon.png'),
  homeBg: require('./HomeBg/icon.png'),
  homeFill: require('./HomeFill/icon.png'),
  leftArrow: require('./LeftArrow/icon.png'),
  location: require('./Location/icon.png'),
  logo: require('./Logo/TMS 01.png'),
  logout: require('./Logout/icon.png'),
  logoWhite: require('./LogoWhite/icon.png'),
  marker: require('./Marker/icon.png'),
  medal: require('./Medal/icon.png'),
  menuBlack: require('./MenuBlack/icon.png'),
  menuCircle: require('./MenuCircle/icon.png'),
  menuGreen: require('./MenuGreen/icon.png'),
  menuWhiteDot: require('./MenuWhiteDot/icon.png'),
  money: require('./Money/icon.png'),
  newMemberImage: require('./NewMemberImage/icon.png'),
  next: require('./Next/icon.png'),
  nextFill: require('./NextFill/icon.png'),
  nextLine: require('./NextLine/icon.png'),
  noButton: require('./NoButton/icon.png'),
  offSwitch: require('./OffSwitch/icon.png'),
  onSwitch: require('./OnSwitch/icon.png'),
  onGoing: require('./OnGoing/icon.png'),
  pencil: require('./Pencil/icon.png'),
  pencilEdit: require('./PencilEdit/icon.png'),
  pencilLine: require('./PencilLine/icon.png'),
  pending: require('./Pending/icon.png'),
  plusBlack: require('./PlusBlack/icon.png'),
  previousArrow: require('./PreviousArrow/icon.png'),
  productFill: require('./ProductFill/icon.png'),
  productLine: require('./ProductLine/icon.png'),
  productPhoto: require('./ProductPhoto/icon.png'),
  profile: require('./Profile/icon.png'),
  profileBlack: require('./ProfileBlack/icon.png'),
  reject: require('./Reject/icon.png'),
  reset: require('./Reset/icon.png'),
  restimonial: require('./Restimonial/icon.png'),
  searchLine: require('./SearchLine/icon.png'),
  selectOff: require('./SelectOff/icon.png'),
  selectOn: require('./SelectOn/icon.png'),
  send: require('./Send/icon.png'),
  share: require('./Share/icon.png'),
  shoppingCartFill: require('./ShoppingCartFill/icon.png'),
  store: require('./Store/icon.png'),
  tickGreen: require('./TickGreen/icon.png'),
  trolley: require('./Trolley/icon.png'),
  categories: require('./Categories/icon.png'),
  categoriesFill: require('./CategoriesFill/icon.png'),
  agent: require('./Agent/icon.png'),
  agentFill: require('./AgentFill/icon.png'),
  menuCircleFill: require('./MenuCircleFill/icon.png'),
  sentFill: require('./SentFill/icon.png'),
  equalizer: require('./Equalizer/icon.png'),
  clinic: require('./Clinic/icon.png'),
  back: require('./Back/icon.png'),
  addFillGray: require('./AddFillGray/plus new.png'),
  addToFill: require('./AddToFill/clipboard.png'),
  Equalizer: require('./Panel/panel.png'),
  backArrow: require('./BackArrow/icon.png'),
  questionMark: require('./RoundedQuestionMark/icon.png'),
  issuesProblem: require('./IssuesProblem/problem.png'),
  bellIcon: require('./BellIcon/icon.png'),
  editLineIcon: require('./EditLine/editing.png'),
  subTask: require('./SubTask/icon.png'),
  imageEdit: require('./ImageEdit/icon.png'),
  updatedProfile: require('./UpdatedProfile/add-photo.png'),
  profilePick: require('./ProfilePick/user.png'),
  basic: require('./Basic/icon.png'),
  advance: require('./Advance/interactivity.png'),
  ticket: require('./Ticket/planning.png'),
  message: require('./Message/icon.png'),
  task: require('./Task/icon.png'),
  issue: require('./Issue/icon.png'),
  company: require('./Company/icon.png'),
  setting: require('./Setting/icon.png'),
  advanceFilter: require('./AdvanceFilter/icon.png'),
  history: require('./History/icon.png'),
  tagUser: require('./TagUser/icon.png'),
  reassignUser: require('./ReassignUser/icon.png'),
  taskStatus: require('./TaskStatus/icon.png'),
  upload: require('./Upload/icon.png'),
  addSub: require('./AddSub/icon.png'),
  markAsClose: require('./MarkAsClose/icon.png'),
  markAsOpen: require('./MarkAsOpen/icon.png'),
  editEta: require('./EditEta/icon.png'),
  Comments: require('./Comments/icon.png'),
  CommentsPink: require('./CommentsPink/icon.png'),
  attachments: require('./Attch/icon.png'),
  attachmentsPink: require('./AttachmentsPink/icon.png'),
  reference: require('./Reference/icon.png'),
  referencePink: require('./ReferencePink/icon.png'),
  timeline: require('./TimelineHistoty/icon.png'),
  users: require('./Users/icon.png'),
  usersPink: require('./UsersPink/icon.png'),
  employeePortfolio: require('./EmployeePortfolio/icon.png'),
  timeSheet: require('./Timesheet/icon.png'),
  attachmentWhiteIcon: require('./AttachmentsWhiteIcons/icon.png'),
  taggedUserWhiteIcon: require('./TaggedUserWhiteIcon/icon.png'),
  statusWhiteIcon: require('./StatusWhiteIcon/icon.png'),
  referenceTaskWhiteIcon: require('./ReferenceTaskWhiteIcon/icon.png'),
  reassignedUserWhiteIcon: require('./ReassignedUserWhiteIcon/icon.png'),
  clockWhiteIcon: require('./Clock/icon.png'),
  startTime: require('./StartTime/icon.png'),
  endTime: require('./EndTime/icon.png'),
  broadCast: require('./BroadcastMessage/icon.png'),
  downArrowBlack: require('./DownArrowBlack/icon.png'),
  videoConference: require('./VideoConference/icon.png'),
  verticalLine: require('./VerticalLine/icon.png'),
  protfolio: require('./Protfolio/icon.png'),
  myTimeSheet: require('./MyTimeSheet/icons.png'),
  previousBackArrow: require('./PreviousBackArrow/icons.png'),
  nextArrow: require('./NextArrow/icons.png'),
  download: require('./Download/icon.png'),
  VideoImage: require('./VideoImage/Icon.png'),
  videoCall: require('./VideoCall/icon.png'),
  VideoCalling: require('./VideoCalling/icon.png'),
  issues: require('./Issues/icon.png'),
  issuesPink: require('./IssuesPink/icon.png'),
  companyInfo: require('./CompanyInfo/icon.png'),
  companyInfoPink: require('./CompanyInfoPink/icon.png'),
  companyTask: require('./CompanyTask/icon.png'),
  companyTaskPink: require('./CompanyTaskPink/icon.png'),
  group: require('./Group/icon.png'),
  admin: require('./Admin/icon.png'),
  vcCall: require('./VcCall/icon.png'),
  deleteRounded: require('./DeleteRounded/icon.png'),
  VideoIcon: require('./VideoIcon/icon1.png'),



  landingImg: require('./LandingImage/Screenshot 2023-07-19 at 4.15.15 PM.png'),
  landingImg1: require('./LandingImage/Screenshot 2023-07-19 at 4.15.33 PM.png'),
  landingImg2: require('./LandingImage/Screenshot 2023-07-19 at 4.17.55 PM.png'),
  landingImg3: require('./LandingImage/Screenshot 2023-07-19 at 4.18.25 PM.png'),
  landingImg4: require('./LandingImage/Screenshot 2023-07-19 at 4.39.20 PM.png'),
  landingImg5: require('./LandingImage/Screenshot 2023-07-19 at 4.43.37 PM.png'),
  landingImg6: require('./LandingImage/Screenshot 2023-07-19 at 4.44.39 PM.png'),
  landingImg7: require('./LandingImage/Screenshot 2023-07-19 at 4.50.20 PM.png'),
  landingImg8: require('./LandingImage/Screenshot 2023-07-19 at 4.57.54 PM.png'),
  landingImg9: require('./LandingImage/Screenshot 2023-07-19 at 4.59.30 PM.png'),
  landingImg10: require('./LandingImage/Screenshot 2023-07-19 at 4.59.37 PM.png'),
  landingImg11: require('./LandingImage/Screenshot 2023-07-19 at 5.01.52 PM.png'),
  landingImg12: require('./LandingImage/Screenshot 2023-07-19 at 5.02.56 PM.png'),
  landingImg13: require('./LandingImage/Screenshot 2023-07-19 at 5.03.08 PM.png'),
  landingImg14: require('./LandingImage/Screenshot 2023-07-19 at 5.03.41 PM.png'),
  landingImg15: require('./LandingImage/Screenshot 2023-07-19 at 5.03.59 PM.png'),
  landingImg16: require('./LandingImage/Screenshot 2023-07-19 at 5.04.12 PM.png'),
  landingImg17: require('./LandingImage/Screenshot 2023-07-19 at 5.04.21 PM.png'),
  landingImg18: require('./LandingImage/Screenshot 2023-07-19 at 5.04.38 PM.png'),
  landingImg19: require('./LandingImage/Screenshot 2023-07-19 at 5.04.53 PM.png'),
  landingImg20: require('./LandingImage/Screenshot 2023-07-19 at 5.05.13 PM.png'),
  landingImg21: require('./LandingImage/Screenshot 2023-07-19 at 5.05.32 PM.png'),
  landingImg22: require('./LandingImage/Screenshot 2023-07-19 at 5.11.16 PM.png'),
  landingImg23: require('./LandingImage/Screenshot 2023-07-19 at 5.12.02 PM.png'),
  landingImg24: require('./LandingImage/Screenshot 2023-07-19 at 5.12.10 PM.png'),
  landingImg25: require('./LandingImage/Screenshot 2023-07-19 at 5.12.18 PM.png'),
  landingImg26: require('./LandingImage/Screenshot 2023-07-19 at 5.12.29 PM.png'),
  landingImg27: require('./LandingImage/Screenshot 2023-07-19 at 5.12.44 PM.png'),
  landingImg28: require('./LandingImage/Screenshot 2023-07-19 at 5.13.09 PM.png'),
  avatarImg: require('./LandingImage/Site Stats-amico (1).png'),
  avatarImg1: require('./LandingImage/Visual data-amico.png'),
  avatarImg2: require('./LandingImage/Visual data-pana.png'),
  avatarImg3: require('./LandingImage/Visual data-rafiki.png'),




};
