
// export const GET_TASK_SUB_GROUP='GET_TASK_SUB_GROUP';
// export const GET_TASK_SUB_GROUP_SUCCESS = 'GET_TASK_SUB_GROUP_SUCCESS';
// export const GET_TASK_SUB_GROUP_FAILURE = 'GET_TASK_SUB_GROUP_FAILURE';
export const RESTORE_USER_COMPANY = 'RESTORE_USER_COMPANY';
export const ADD_TASK_GROUP='ADD_TASK_GROUP';
export const ADD_TASK_GROUP_SUCCESS = 'ADD_TASK_GROUP_SUCCESS';
export const ADD_TASK_GROUP_FAILURE = 'ADD_TASK_GROUP_FAILURE';
export const GET_TASK_GROUP='GET_TASK_GROUP';
export const GET_TASK_GROUP_SUCCESS = 'GET_TASK_GROUP_SUCCESS';
export const GET_TASK_GROUP_FAILURE = 'GET_TASK_GROUP_FAILURE';

export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
export const ADD_DEPARTMENT_SUCCESS = "ADD_DEPARTMENT_SUCCESS";
export const ADD_DEPARTMENT_FAILURE = "ADD_DEPARTMENT_FAILURE";

export const ADD_DESIGNATION = "ADD_DESIGNATION";
export const ADD_DESIGNATION_SUCCESS = "ADD_DESIGNATION_SUCCESS";
export const ADD_DESIGNATION_FAILURE = "ADD_DESIGNATION_FAILURE";

export const FETCH_DESIGNATION = "FETCH_DESIGNATION";
export const FETCH_DESIGNATION_SUCCESS = "FETCH_DESIGNATION_SUCCESS";
export const FETCH_DESIGNATION_FAILURE = "FETCH_DESIGNATION_FAILURE";

export const FETCH_DEPARTMENT = "FETCH_DEPARTMENT";
export const FETCH_DEPARTMENT_SUCCESS = "FETCH_DEPARTMENT_SUCCESS";
export const FETCH_DEPARTMENT_FAILURE = "FETCH_DEPARTMENT_FAILURE";


export const ADD_BRAND_SECTOR = "ADD_BRAND_SECTOR ";
export const ADD_BRAND_SECTOR_SUCCESS = "ADD_BRAND_SECTOR_SUCCESS";
export const ADD_BRAND_SECTOR_FAILURE = "ADD_BRAND_SECT6OR_FAILURE";

export const ADD_TICKET_TAG = "ADD_TICKET_TAG";
export const ADD_TICKET_TAG_SUCCESS = "ADD_TICKET_TAG_SUCCESS";
export const ADD_TICKET_TAG_FAILURE = " ADD_TICKET_TAG_FAILURE";

export const  GET_BRAND_SECTOR  = "GET_BRAND_SECTOR";
export const  GET_BRAND_SECTOR_SUCCESS = "GET_BRAND_SECTOR_SUCCESS";
export const  GET_BRAND_SECTOR_FAILURE = "GET_BRAND_SECT6OR_FAILURE";

export const GET_TICKET_TAG = "GET_TICKET_TAG";
export const GET_TICKET_TAG_SUCCESS = "GET_TICKET_TAG_SUCCESS";
export const GET_TICKET_TAG_FAILURE = "GET_TICKET_TAG_FAILURE";
