

export const RESTORE_USER_COMPANY = 'RESTORE_USER_COMPANY';
export const ADD_TASK_GROUP = 'ADD_TASK_GROUP';
export const ADD_TASK_GROUP_SUCCESS = 'ADD_TASK_GROUP_SUCCESS';
export const ADD_TASK_GROUP_FAILURE = 'ADD_TASK_GROUP_FAILURE';
export const GET_TASK_GROUP = 'GET_TASK_GROUP';
export const GET_TASK_GROUP_SUCCESS = 'GET_TASK_GROUP_SUCCESS';
export const GET_TASK_GROUP_FAILURE = 'GET_TASK_GROUP_FAILURE';

export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
export const ADD_DEPARTMENT_SUCCESS = "ADD_DEPARTMENT_SUCCESS";
export const ADD_DEPARTMENT_FAILURE = "ADD_DEPARTMENT_FAILURE";

export const ADD_DESIGNATION = "ADD_DESIGNATION";
export const ADD_DESIGNATION_SUCCESS = "ADD_DESIGNATION_SUCCESS";
export const ADD_DESIGNATION_FAILURE = "ADD_DESIGNATION_FAILURE";

export const FETCH_DESIGNATION = "FETCH_DESIGNATION";
export const FETCH_DESIGNATION_SUCCESS = "FETCH_DESIGNATION_SUCCESS";
export const FETCH_DESIGNATION_FAILURE = "FETCH_DESIGNATION_FAILURE";

export const FETCH_DEPARTMENT = "FETCH_DEPARTMENT";
export const FETCH_DEPARTMENT_SUCCESS = "FETCH_DEPARTMENT_SUCCESS";
export const FETCH_DEPARTMENT_FAILURE = "FETCH_DEPARTMENT_FAILURE";


export const ADD_BRAND_SECTOR = "ADD_BRAND_SECTOR ";
export const ADD_BRAND_SECTOR_SUCCESS = "ADD_BRAND_SECTOR_SUCCESS";
export const ADD_BRAND_SECTOR_FAILURE = "ADD_BRAND_SECT6OR_FAILURE";

export const ADD_TICKET_TAG = "ADD_TICKET_TAG";
export const ADD_TICKET_TAG_SUCCESS = "ADD_TICKET_TAG_SUCCESS";
export const ADD_TICKET_TAG_FAILURE = " ADD_TICKET_TAG_FAILURE";

export const GET_BRAND_SECTOR = "GET_BRAND_SECTOR";
export const GET_BRAND_SECTOR_SUCCESS = "GET_BRAND_SECTOR_SUCCESS";
export const GET_BRAND_SECTOR_FAILURE = "GET_BRAND_SECT6OR_FAILURE";

export const GET_TICKET_TAG = "GET_TICKET_TAG";
export const GET_TICKET_TAG_SUCCESS = "GET_TICKET_TAG_SUCCESS";
export const GET_TICKET_TAG_FAILURE = "GET_TICKET_TAG_FAILURE";


export const GET_ASSOCIATED_BRANCH = 'GET_ASSOCIATED_BRANCH';
export const GET_ASSOCIATED_BRANCH_SUCCESS = 'GET_ASSOCIATED_BRANCH_SUCCESS';
export const GET_ASSOCIATED_BRANCH_FAILURE = 'GET_ASSOCIATED_BRANCH_FAILURE';

export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS';
export const ADD_EMPLOYEE_FAILURE = 'ADD_EMPLOYEE_FAILURE';

export const UPDATE_EMPLOYEE_PROFILE_PHOTO = 'UPDATE_EMPLOYEE_PROFILE_PHOTO';
export const UPDATE_EMPLOYEE_PROFILE_PHOTO_SUCCESS = 'UPDATE_EMPLOYEE_PROFILE_PHOTO_SUCCESS';
export const UPDATE_EMPLOYEE_PROFILE_PHOTO_FAILURE = 'UPDATE_EMPLOYEE_PROFILE_PHOTO_FAILURE';


export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_FAILURE = 'GET_EMPLOYEES_FAILURE';


export const GET_EMPLOYEESL = 'GET_EMPLOYEESL';
export const GET_EMPLOYEES_SUCCESSL = 'GET_EMPLOYEES_SUCCESSL';
export const GET_EMPLOYEES_FAILUREL = 'GET_EMPLOYEES_FAILUREL';

export const GET_EMPLOYEE_TIMELINE = 'GET_EMPLOYEE_TIMELINE';
export const GET_EMPLOYEE_TIMELINE_SUCCESS = 'GET_EMPLOYEE_TIMELINE_SUCCESS';
export const GET_EMPLOYEE_TIMELINE_FAILURE = 'GET_EMPLOYEE_TIMELINE_FAILURE';

export const ADD_EMPLOYEE_TIMELINE = 'ADD_EMPLOYEE_TIMELINE';
export const ADD_EMPLOYEE_TIMELINE_SUCCESS = 'ADD_EMPLOYEE_TIMELINE_SUCCESS';
export const ADD_EMPLOYEE_TIMELINE_FAILURE = 'ADD_EMPLOYEE_TIMELINE_FAILURE';

export const REGISTER_ADMIN = 'REGISTER_ADMIN';
export const REGISTER_ADMIN_SUCCESS = 'REGISTER_ADMIN_SUCCESS';
export const REGISTER_ADMIN_FAILURE = 'REGISTER_ADMIN_FAILURE';

export const REGISTER_COMPANY = 'REGISTER_COMPANY';
export const REGISTER_COMPANY_SUCCESS = 'REGISTER_COMPANY_SUCCESS';
export const REGISTER_COMPANY_FAILURE = 'REGISTER_COMPANY_FAILURE';



/**
 * GET_ASSOCIATED_COMPANIES_L
 */

export const GET_ASSOCIATED_COMPANIES_L = 'GET_ASSOCIATED_COMPANIES_L';
export const GET_ASSOCIATED_COMPANIES_L_SUCCESS = 'GET_ASSOCIATED_COMPANIES_L_SUCCESS';
export const GET_ASSOCIATED_COMPANIES_L_FAILURE = 'GET_ASSOCIATED_COMPANIES_L_FAILURE';

/**
 * GET DASHBOARD
 */

export const GET_DASHBOARD = 'GET_DASHBOARD';
export const GET_DASHBOARD_SUCCESS = 'GET_DASHBOARD_SUCCESS';
export const GET_DASHBOARD_FAILURE = 'GET_DASHBOARD_FAILURE';


/**
 * POST VIDEO CONFERENCE
 */

export const POST_VIDEO_CONFERENCE = 'POST_VIDEO_CONFERENCE';
export const POST_VIDEO_CONFERENCE_SUCCESS = 'POST_VIDEO_CONFERENCE_SUCCESS';
export const POST_VIDEO_CONFERENCE_FAILURE = 'POST_VIDEO_CONFERENCE_FAILURE';

/**
* GET_VIDEO_CONFERENCE_LIST
 */

export const GET_VIDEO_CONFERENCE_LIST = 'GET_VIDEO_CONFERENCE_LIST';
export const GET_VIDEO_CONFERENCE_LIST_SUCCESS = 'GET_VIDEO_CONFERENCE_LIST_SUCCESS';
export const GET_VIDEO_CONFERENCE_LIST_FAILURE = 'GET_VIDEO_CONFERENCE_LIST_FAILURE';

/**
 * POST VIDEO CONFERENCE
 */

export const GET_TOKEN_BY_USER = 'GET_TOKEN_BY_USER';
export const GET_TOKEN_BY_USER_SUCCESS = 'GET_TOKEN_BY_USER_SUCCESS';
export const GET_TOKEN_BY_USER_FAILURE = 'GET_TOKEN_BY_USER_FAILURE';


/**
 * set selected company
 */

export const SET_SELECTED_COMPANY = 'SET_SELECTED_COMPANY';

export const SET_SELECTED_EMPLOYEE = 'SET_SELECTED_EMPLOYEE';


