

export const RESTORE_USER_COMPANY = 'RESTORE_USER_COMPANY';
export const ADD_TASK_GROUP = 'ADD_TASK_GROUP';
export const ADD_TASK_GROUP_SUCCESS = 'ADD_TASK_GROUP_SUCCESS';
export const ADD_TASK_GROUP_FAILURE = 'ADD_TASK_GROUP_FAILURE';
export const GET_TASK_GROUP = 'GET_TASK_GROUP';
export const GET_TASK_GROUP_SUCCESS = 'GET_TASK_GROUP_SUCCESS';
export const GET_TASK_GROUP_FAILURE = 'GET_TASK_GROUP_FAILURE';

export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
export const ADD_DEPARTMENT_SUCCESS = "ADD_DEPARTMENT_SUCCESS";
export const ADD_DEPARTMENT_FAILURE = "ADD_DEPARTMENT_FAILURE";

export const ADD_DESIGNATION = "ADD_DESIGNATION";
export const ADD_DESIGNATION_SUCCESS = "ADD_DESIGNATION_SUCCESS";
export const ADD_DESIGNATION_FAILURE = "ADD_DESIGNATION_FAILURE";

export const FETCH_DESIGNATION = "FETCH_DESIGNATION";
export const FETCH_DESIGNATION_SUCCESS = "FETCH_DESIGNATION_SUCCESS";
export const FETCH_DESIGNATION_FAILURE = "FETCH_DESIGNATION_FAILURE";

export const FETCH_DEPARTMENT = "FETCH_DEPARTMENT";
export const FETCH_DEPARTMENT_SUCCESS = "FETCH_DEPARTMENT_SUCCESS";
export const FETCH_DEPARTMENT_FAILURE = "FETCH_DEPARTMENT_FAILURE";


export const ADD_BRAND_SECTOR = "ADD_BRAND_SECTOR ";
export const ADD_BRAND_SECTOR_SUCCESS = "ADD_BRAND_SECTOR_SUCCESS";
export const ADD_BRAND_SECTOR_FAILURE = "ADD_BRAND_SECT6OR_FAILURE";

export const ADD_TICKET_TAG = "ADD_TICKET_TAG";
export const ADD_TICKET_TAG_SUCCESS = "ADD_TICKET_TAG_SUCCESS";
export const ADD_TICKET_TAG_FAILURE = " ADD_TICKET_TAG_FAILURE";

export const GET_BRAND_SECTOR = "GET_BRAND_SECTOR";
export const GET_BRAND_SECTOR_SUCCESS = "GET_BRAND_SECTOR_SUCCESS";
export const GET_BRAND_SECTOR_FAILURE = "GET_BRAND_SECT6OR_FAILURE";

export const GET_TICKET_TAG = "GET_TICKET_TAG";
export const GET_TICKET_TAG_SUCCESS = "GET_TICKET_TAG_SUCCESS";
export const GET_TICKET_TAG_FAILURE = "GET_TICKET_TAG_FAILURE";


export const GET_ASSOCIATED_BRANCH = 'GET_ASSOCIATED_BRANCH';
export const GET_ASSOCIATED_BRANCH_SUCCESS = 'GET_ASSOCIATED_BRANCH_SUCCESS';
export const GET_ASSOCIATED_BRANCH_FAILURE = 'GET_ASSOCIATED_BRANCH_FAILURE';

export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS';
export const ADD_EMPLOYEE_FAILURE = 'ADD_EMPLOYEE_FAILURE';

export const UPDATE_EMPLOYEE_PROFILE_PHOTO = 'UPDATE_EMPLOYEE_PROFILE_PHOTO';
export const UPDATE_EMPLOYEE_PROFILE_PHOTO_SUCCESS = 'UPDATE_EMPLOYEE_PROFILE_PHOTO_SUCCESS';
export const UPDATE_EMPLOYEE_PROFILE_PHOTO_FAILURE = 'UPDATE_EMPLOYEE_PROFILE_PHOTO_FAILURE';


export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_FAILURE = 'GET_EMPLOYEES_FAILURE';


export const GET_EMPLOYEESL = 'GET_EMPLOYEESL';
export const GET_EMPLOYEESL_SUCCESS = 'GET_EMPLOYEESL_SUCCESS';
export const GET_EMPLOYEESL_FAILURE = 'GET_EMPLOYEESL_FAILURE';

export const GET_EMPLOYEE_TIMELINE = 'GET_EMPLOYEE_TIMELINE';
export const GET_EMPLOYEE_TIMELINE_SUCCESS = 'GET_EMPLOYEE_TIMELINE_SUCCESS';
export const GET_EMPLOYEE_TIMELINE_FAILURE = 'GET_EMPLOYEE_TIMELINE_FAILURE';

export const ADD_EMPLOYEE_TIMELINE = 'ADD_EMPLOYEE_TIMELINE';
export const ADD_EMPLOYEE_TIMELINE_SUCCESS = 'ADD_EMPLOYEE_TIMELINE_SUCCESS';
export const ADD_EMPLOYEE_TIMELINE_FAILURE = 'ADD_EMPLOYEE_TIMELINE_FAILURE';

export const REGISTER_ADMIN = 'REGISTER_ADMIN';
export const REGISTER_ADMIN_SUCCESS = 'REGISTER_ADMIN_SUCCESS';
export const REGISTER_ADMIN_FAILURE = 'REGISTER_ADMIN_FAILURE';

export const REGISTER_COMPANY = 'REGISTER_COMPANY';
export const REGISTER_COMPANY_SUCCESS = 'REGISTER_COMPANY_SUCCESS';
export const REGISTER_COMPANY_FAILURE = 'REGISTER_COMPANY_FAILURE';


export const GET_EVENTS = 'GET_EVENTS';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_FAILURE = 'GET_EVENTS_FAILURE';

export const ADD_EVENT = 'ADD_EVENT';
export const ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS';
export const ADD_EVENT_FAILURE = 'ADD_EVENT_FAILURE';



/**
 * GET_ASSOCIATED_COMPANIES_L
 */

export const GET_ASSOCIATED_COMPANIES_L = 'GET_ASSOCIATED_COMPANIES_L';
export const GET_ASSOCIATED_COMPANIES_L_SUCCESS = 'GET_ASSOCIATED_COMPANIES_L_SUCCESS';
export const GET_ASSOCIATED_COMPANIES_L_FAILURE = 'GET_ASSOCIATED_COMPANIES_L_FAILURE';

/**
 * GET DASHBOARD
 */

export const GET_DASHBOARD = 'GET_DASHBOARD';
export const GET_DASHBOARD_SUCCESS = 'GET_DASHBOARD_SUCCESS';
export const GET_DASHBOARD_FAILURE = 'GET_DASHBOARD_FAILURE';


/**
 * POST VIDEO CONFERENCE
 */

export const POST_VIDEO_CONFERENCE = 'POST_VIDEO_CONFERENCE';
export const POST_VIDEO_CONFERENCE_SUCCESS = 'POST_VIDEO_CONFERENCE_SUCCESS';
export const POST_VIDEO_CONFERENCE_FAILURE = 'POST_VIDEO_CONFERENCE_FAILURE';

/**
* GET_VIDEO_CONFERENCE_LIST
 */

export const GET_VIDEO_CONFERENCE_LIST = 'GET_VIDEO_CONFERENCE_LIST';
export const GET_VIDEO_CONFERENCE_LIST_SUCCESS = 'GET_VIDEO_CONFERENCE_LIST_SUCCESS';
export const GET_VIDEO_CONFERENCE_LIST_FAILURE = 'GET_VIDEO_CONFERENCE_LIST_FAILURE';

/**
 * POST VIDEO CONFERENCE
 */

export const GET_TOKEN_BY_USER = 'GET_TOKEN_BY_USER';
export const GET_TOKEN_BY_USER_SUCCESS = 'GET_TOKEN_BY_USER_SUCCESS';
export const GET_TOKEN_BY_USER_FAILURE = 'GET_TOKEN_BY_USER_FAILURE';


/**
 * set selected company
 */

export const SET_SELECTED_COMPANY = 'SET_SELECTED_COMPANY';

export const SET_SELECTED_EMPLOYEE = 'SET_SELECTED_EMPLOYEE';

/**
 * GET ASSOCIATED COMPANIES
 */

export const GET_ASSOCIATED_COMPANY = 'GET_ASSOCIATED_COMPANY';
export const GET_ASSOCIATED_COMPANY_SUCCESS = 'GET_ASSOCIATED_COMPANY_SUCCESS';
export const GET_ASSOCIATED_COMPANY_FAILURE = 'GET_ASSOCIATED_COMPANY_FAILURE';

/**
 * ADD ASSOCIATED COMPANIES
 */

export const ADD_ASSOCIATED_COMPANY = 'ADD_ASSOCIATED_COMPANY';
export const ADD_ASSOCIATED_COMPANY_SUCCESS = 'ADD_ASSOCIATED_COMPANY_SUCCESS';
export const ADD_ASSOCIATED_COMPANY_FAILURE = 'ADD_ASSOCIATED_COMPANY_FAILURE';

/* REFRESH USER COMPANY */

export const REFRESH_USER_COMPANY = 'REFRESH_TASK_EVENTS';
// get groups Employees
export const GET_GROUPS_EMPLOYEES = 'GET_GROUP_EMPLOYEES'
export const GET_GROUPS_EMPLOYEES_SUCCESS = 'GET_GROUP_EMPLOYEES_SUCCESS'
export const GET_GROUPS_EMPLOYEES_FAILURE = 'GET_GROUP_EMPLOYEES_FAILURE'

// get group Message
export const GET_GROUP_MESSAGE = 'GET_GROUP_MESSAGE'
export const GET_GROUP_MESSAGE_SUCCESS = 'GET_GROUP_MESSAGE_SUCCESS'
export const GET_GROUP_MESSAGE_FAILURE = 'GET_GROUP_MESSAGE_FAILURE'

// ADD group Message
export const ADD_GROUP_MESSAGE = 'ADD_GROUP_MESSAGE'
export const ADD_GROUP_MESSAGE_SUCCESS = 'ADD_GROUP_MESSAGE_SUCCESS'
export const ADD_GROUP_MESSAGE_FAILURE = 'ADD_GROUP_MESSAGE_FAILURE'

// ADD task sub group
export const GET_SUB_GROUP = 'ET_SUB_GROUP'
export const GET_SUB_GROUP_SUCCESS = 'GET_SUB_GROUP_SUCCESS'
export const GET_SUB_GROUP_FAILURE = 'GET_SUB_GROUP_FAILURE'

/**
 * refresh task Events
 */

export const REFRESH_GROUP_EVENTS = 'REFRESH_GROUP_EVENTS';

//GROUOP MESSAGE
export const REFRESH_CHAT_MESSAGE = 'REFRESH_CHAT_MESSAGE';

/* Group */
export const SELECTED_GROUP_ITEM = 'SELECTED_GROUP_ITEM';


/* GroupChat  */
export const SELECTED_GROUP_CHAT = 'SELECTED_GROUP_CHAT';


//ADD GROUP USE
export const ADD_GROUP_USER = 'ADD_GROUP_USER'
export const ADD_GROUP_USER_SUCCESS = 'ADD_GROUP_USER_SUCCESS'
export const ADD_GROUP_USER_FAILURE = 'ADD_GROUP_USER_FAILURE'

//GET GROUP
export const GET_CHAT_GROUPS = 'GET_CHAT_GROUPS'
export const GET_CHAT_GROUPS_SUCCESS = 'GET_CHAT_GROUPS_SUCCESS'
export const GET_CHAT_GROUPS_FAILURE = 'GET_CHAT_GROUPS_FAILURE'

//group code
export const SELECTED_TASK_GROUP_CODE = 'SELECTED_TASK_GROUP_CODE';

export const REFRESH_GROUP_CHAT = 'REFRESH_GROUP_CHAT';


//employee time status
export const EMPLOYEE_TIMELINE_STATUS = 'EMPLOYEE_TIMELINE_STATUS'
export const EMPLOYEE_TIMELINE_STATUS_SUCCESS = 'EMPLOYEE_TIMELINE_STATUS_SUCCESS'
export const EMPLOYEE_TIMELINE_STATUS_FAILURE = ' EMPLOYEE_TIMELINE_STATUS_FAILURE'


//ADD_ENABLE_REQUEST
export const ADD_ENABLE_REQUEST = ' ADD_ENABLE_REQUEST'
export const ADD_ENABLE_REQUEST_SUCCESS = ' ADD_ENABLE_REQUEST_SUCCESS'
export const ADD_ENABLE_REQUEST_FAILURE = '  ADD_ENABLE_REQUEST_FAILURE'

//GET_ENABLE_REQUEST
export const GET_ENABLE_REQUEST = ' GET_ENABLE_REQUEST'
export const GET_ENABLE_REQUEST_SUCCESS = 'GET_ENABLE_REQUEST_SUCCESS'
export const GET_ENABLE_REQUEST_FAILURE = '  GET_ENABLE_REQUEST_FAILURE'



//selected vc details

export const SELECTED_VC_DETAILS = 'SELECTED_VC_DETAILS';


//vc notification details

export const VC_NOTIFICATION_DETAILS = 'VC_NOTIFICATION_DETAILS';


//post chat message

export const POST_CHAT_MESSAGE = ' POST_CHAT_MESSAGE'
export const POST_CHAT_MESSAGE_SUCCESS = 'POST_CHAT_MESSAGE_SUCCESS'
export const POST_CHAT_MESSAGE_FAILURE = 'POST_CHAT_MESSAGE_FAILURE'


//GET chat message

export const FETCH_CHAT_MESSAGE = ' FETCH_CHAT_MESSAGE'
export const FETCH_CHAT_MESSAGE_SUCCESS = 'FETCH_CHAT_MESSAGE_SUCCESS'
export const FETCH_CHAT_MESSAGE_FAILURE = 'FETCH_CHAT_MESSAGE_FAILURE'

///get chat employee list

export const FETCH_CHAT_EMPLOYEE_LIST = ' FETCH_CHAT_EMPLOYEE_LIST'
export const FETCH_CHAT_EMPLOYEE_LIST_SUCCESS = 'FETCH_CHAT_EMPLOYEE_LIST_SUCCESS'
export const FETCH_CHAT_EMPLOYEE_LIST_FAILURE = 'FETCH_CHAT_EMPLOYEE_LIST_FAILURE'


//vc notification details

export const HANDLE_ONE_TO_ONE_CHAT = 'HANDLE_ONE_TO_ONE_CHAT';


//vc notification details

export const ONE_TO_ONE_VC_NOTI = 'ONE_TO_ONE_VC_NOTI';

//selectedPrivateUser

export const USER_CHAT = 'USER_CHAT';



export const REFRESH_PRIVATE_CHAT = 'REFRESH_PRIVATE_CHAT';


export const USER_DETAILS_DATA = 'USER_DETAILS_DATA'