/**
 *  get Store details
 */

export const GET_STORE_DETAILS = 'GET_STORE_DETAILS';
export const GET_STORE_DETAILS_SUCCESS = 'GET_STORE_DETAILS_SUCCESS';
export const GET_STORE_DETAILS_FAILURE = 'GET_STORE_DETAILS_FAILURE';