export const GET_ASSOCIATED_BRANCH = 'GET_ASSOCIATED_BRANCH';
export const GET_ASSOCIATED_BRANCH_SUCCESS = 'GET_ASSOCIATED_BRANCH_SUCCESS';
export const GET_ASSOCIATED_BRANCH_FAILURE = 'GET_ASSOCIATED_BRANCH_FAILURE';

export const GET_ASSOCIATED_COMPANY_BRANCH = 'GET_ASSOCIATED_COMPANY_BRANCH';
export const GET_ASSOCIATED_COMPANY_BRANCH_SUCCESS = 'GET_ASSOCIATED_COMPANY_BRANCH_SUCCESS';
export const GET_ASSOCIATED_COMPANY_BRANCH_FAILURE = 'GET_ASSOCIATED_COMPANY_BRANCH_FAILURE';

export const GET_DASHBOARD = 'GET_DASHBOARD';
export const GET_DASHBOARD_SUCCESS = 'GET_DASHBOARD_SUCCESS';
export const GET_DASHBOARD_FAILURE = 'GET_DASHBOARD_FAILURE';

/**
 *  issues selected item
 */

export const SET_SELECTED_ISSUES = 'SET_SELECTED_ISSUES';
export const SET_REFERENCE_SELECTED_ISSUES = 'SET_REFERENCE_SELECTED_ISSUES';

/**
 * setting
 */
 export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
 export const ADD_DEPARTMENT_SUCCESS = "ADD_DEPARTMENT_SUCCESS";
 export const ADD_DEPARTMENT_FAILURE = "ADD_DEPARTMENT_FAILURE";

 export const ADD_DESIGNATION = "ADD_DESIGNATION";
export const ADD_DESIGNATION_SUCCESS = "ADD_DESIGNATION_SUCCESS";
export const ADD_DESIGNATION_FAILURE = "ADD_DESIGNATION_FAILURE";

export const FETCH_DESIGNATION = "FETCH_DESIGNATION";
export const FETCH_DESIGNATION_SUCCESS = "FETCH_DESIGNATION_SUCCESS";
export const FETCH_DESIGNATION_FAILURE = "FETCH_DESIGNATION_FAILURE";

export const FETCH_DEPARTMENT = "FETCH_DEPARTMENT";
export const FETCH_DEPARTMENT_SUCCESS = "FETCH_DEPARTMENT_SUCCESS";
export const FETCH_DEPARTMENT_FAILURE = "FETCH_DEPARTMENT_FAILURE";


export const ADD_BRAND_SECTOR = "ADD_BRAND_SECTOR ";
export const ADD_BRAND_SECTOR_SUCCESS = "ADD_BRAND_SECTOR_SUCCESS";
export const ADD_BRAND_SECTOR_FAILURE = "ADD_BRAND_SECT6OR_FAILURE";

export const ADD_TICKET_TAG = "ADD_TICKET_TAG";
export const ADD_TICKET_TAG_SUCCESS = "ADD_TICKET_TAG_SUCCESS";
export const ADD_TICKET_TAG_FAILURE = " ADD_TICKET_TAG_FAILURE";

export const  GET_BRAND_SECTOR  = "GET_BRAND_SECTOR";
export const  GET_BRAND_SECTOR_SUCCESS = "GET_BRAND_SECTOR_SUCCESS";
export const  GET_BRAND_SECTOR_FAILURE = "GET_BRAND_SECT6OR_FAILURE";

export const GET_TICKET_TAG = "GET_TICKET_TAG";
export const GET_TICKET_TAG_SUCCESS = "GET_TICKET_TAG_SUCCESS";
export const GET_TICKET_TAG_FAILURE = "GET_TICKET_TAG_FAILURE";


export const COMPANY_SELECTED_DETAILS ="COMPANY_SELECTED_DETAILS";

export const REFERENCE_ISSUE_DETAILS ="REFERENCE_ISSUE_DETAILS" ; 

export const RESTORE_ADMIN="RESTORE_ADMIN" ; 

/* Task */
export const GET_TASKS = 'GET_TASKS';
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const GET_TASKS_FAILURE = 'GET_TASKS_FAILURE';

export const ADD_TASK = 'ADD_TASK';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_FAILURE = 'ADD_TASK_FAILURE';

export const GET_SUB_TASKS = 'GET_SUB_TASKS';
export const GET_SUB_TASKS_SUCCESS = 'GET_SUB_TASKS_SUCCESS';
export const GET_SUB_TASKS_FAILURE = 'GET_SUB_TASKS_FAILURE';

export const GET_TASKS_ITEM = 'GET_TASKS_ITEM';

export const GET_REFERENCE_TASKS='GET_REFERENCE_TASKS';
export const GET_REFERENCE_TASKS_SUCCESS='GET_REFERENCE_TASKS_SUCCESS';
export const GET_REFERENCE_TASKS_FAILURE='GET_REFERENCE_TASKS_FAILURE';
export const GET_TASK_USERS = 'GET_TASK_USERS';
export const GET_TASK_USERS_SUCCESS = 'GET_TASK_USERS_SUCCESS';
export const GET_TASK_USERS_FAILURE = 'GET_TASK_USERS_FAILURE';

export const GET_TICKET_USERS = 'GET_TICKET_USERS';
export const GET_TICKET_USERS_SUCCESS = 'GET_TICKET_USERS_SUCCESS';
export const GET_TICKET_USERS_FAILURE = 'GET_TICKET_USERS_FAILURE';

export const GET_CURRENT_PAGE='GET_CURRENT_PAGE';

export const GET_TASK_GROUP='GET_TASK_GROUP';
export const GET_TASK_GROUP_SUCCESS = 'GET_TASK_GROUP_SUCCESS';
export const GET_TASK_GROUP_FAILURE = 'GET_TASK_GROUP_FAILURE';



export const ADD_TASK_GROUP='ADD_TASK_GROUP';
export const ADD_TASK_GROUP_SUCCESS = 'ADD_TASK_GROUP_SUCCESS';
export const ADD_TASK_GROUP_FAILURE = 'ADD_TASK_GROUP_FAILURE';


