export const GET_ASSOCIATED_BRANCH = 'GET_ASSOCIATED_BRANCH';
export const GET_ASSOCIATED_BRANCH_SUCCESS = 'GET_ASSOCIATED_BRANCH_SUCCESS';
export const GET_ASSOCIATED_BRANCH_FAILURE = 'GET_ASSOCIATED_BRANCH_FAILURE';

export const GET_DASHBOARD = 'GET_DASHBOARD';
export const GET_DASHBOARD_SUCCESS = 'GET_DASHBOARD_SUCCESS';
export const GET_DASHBOARD_FAILURE = 'GET_DASHBOARD_FAILURE';

/**
 *  issues selected item
 */

export const SET_SELECTED_ISSUES = 'SET_SELECTED_ISSUES';

/**
 * setting
 */
 export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
 export const ADD_DEPARTMENT_SUCCESS = "ADD_DEPARTMENT_SUCCESS";
 export const ADD_DEPARTMENT_FAILURE = "ADD_DEPARTMENT_FAILURE";

 export const ADD_DESIGNATION = "ADD_DESIGNATION";
export const ADD_DESIGNATION_SUCCESS = "ADD_DESIGNATION_SUCCESS";
export const ADD_DESIGNATION_FAILURE = "ADD_DESIGNATION_FAILURE";

export const FETCH_DESIGNATION = "FETCH_DESIGNATION";
export const FETCH_DESIGNATION_SUCCESS = "FETCH_DESIGNATION_SUCCESS";
export const FETCH_DESIGNATION_FAILURE = "FETCH_DESIGNATION_FAILURE";

export const FETCH_DEPARTMENT = "FETCH_DEPARTMENT";
export const FETCH_DEPARTMENT_SUCCESS = "FETCH_DEPARTMENT_SUCCESS";
export const FETCH_DEPARTMENT_FAILURE = "FETCH_DEPARTMENT_FAILURE";

export const COMPANY_SELECTED_DETAILS ="COMPANY_SELECTED_DETAILS";

export const REFERENCE_ISSUE_DETAILS ="REFERENCE_ISSUE_DETAILS" ; 
