

export const GET_ASSOCIATED_COMPANY_BRANCH = 'GET_ASSOCIATED_COMPANY_BRANCH';
export const GET_ASSOCIATED_COMPANY_BRANCH_SUCCESS = 'GET_ASSOCIATED_COMPANY_BRANCH_SUCCESS';
export const GET_ASSOCIATED_COMPANY_BRANCH_FAILURE = 'GET_ASSOCIATED_COMPANY_BRANCH_FAILURE';



/**
 *  issues selected item
 */

export const SET_SELECTED_ISSUES = 'SET_SELECTED_ISSUES';
export const SET_REFERENCE_SELECTED_ISSUES = 'SET_REFERENCE_SELECTED_ISSUES';

export const COMPANY_SELECTED_DETAILS = "COMPANY_SELECTED_DETAILS";

export const REFERENCE_ISSUE_DETAILS = "REFERENCE_ISSUE_DETAILS";

export const RESTORE_ADMIN = "RESTORE_ADMIN";



export const ADD_TASK = 'ADD_TASK';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_FAILURE = 'ADD_TASK_FAILURE';



export const GET_TASKS_ITEM = 'GET_TASKS_ITEM';



export const GET_TICKET_USERS = 'GET_TICKET_USERS';
export const GET_TICKET_USERS_SUCCESS = 'GET_TICKET_USERS_SUCCESS';
export const GET_TICKET_USERS_FAILURE = 'GET_TICKET_USERS_FAILURE';

export const GET_CURRENT_PAGE = 'GET_CURRENT_PAGE';



export const GET_REFERENCE_ID = 'GET_REFERENCE_ID'

export const GET_SUBTASK_ID = 'GET_SUBTASK_ID';

export const LOGIN_USER = 'LOGIN_USER';

export const GET_TASK_SUB_GROUP = 'GET_TASK_SUB_GROUP';
export const GET_TASK_SUB_GROUP_SUCCESS = 'GET_TASK_SUB_GROUP_SUCCESS';
export const GET_TASK_SUB_GROUP_FAILURE = 'GET_TASK_SUB_GROUP_FAILURE';
export const GET_TASK_HISTORY = 'GET_TASK_HISTORY';
export const GET_TASK_HISTORY_SUCCESS = 'GET_TASK_HISTORY_SUCCESS';
export const GET_TASK_HISTORY_FAILURE = 'GET_TASK_HISTORY_FAILURE';



