export const FETCH_TASK_DETAILS = 'FETCH_TASK_DETAILS';
export const FETCH_TASK_DETAILS_SUCCESS = 'FETCH_TASK_DETAILS_SUCCESS';
export const FETCH_TASK_DETAILS_FAILURE = 'FETCH_TASK_DETAILS_FAILURE'

export const FETCH_COURSES = 'FETCH_COURSES';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const FETCH_COURSES_FAILURE = 'FETCH_COURSES_FAILURE'

export const FETCH_COURSE_TOPICS = 'FETCH_COURSES_TOPICS';
export const FETCH_COURSE_TOPICS_SUCCESS = 'FETCH_COURSES_TOPICS_SUCCESS';
export const FETCH_COURSE_TOPICS_FAILURE = 'FETCH_COURSES_TOPICS_FAILURE'

export const FETCH_COURSE_TOPIC_TASKS = 'FETCH_COURSE_TOPIC_TASKS';
export const FETCH_COURSE_TOPIC_TASKS_SUCCESS = 'FETCH_COURSE_TOPIC_TASKS_SUCCESS';
export const FETCH_COURSE_TOPIC_TASKS_FAILURE = 'FETCH_COURSE_TOPIC_TASKS_FAILURE'

export const SET_COURSE_TOPIC_NAME = 'SET_COURSE_TOPIC_NAME'

export const POST_GENERIC_CRUD_DETAILS = 'POST_GENERIC_CRUD_DETAILS';
export const POST_GENERIC_CRUD_DETAILS_SUCCESS = 'POST_GENERIC_CRUD_DETAILS_SUCCESS';
export const POST_GENERIC_CRUD_DETAILS_FAILURE = 'POST_GENERIC_CRUD_DETAILS_FAILURE'

export const POST_GENERIC_BATCH_CRUD_DETAILS = 'POST_GENERIC_BATCH_CRUD_DETAILS';
export const POST_GENERIC_BATCH_CRUD_DETAILS_SUCCESS = 'POST_GENERIC_BATCH_CRUD_DETAILS_SUCCESS';
export const POST_GENERIC_BATCH_CRUD_DETAILS_FAILURE = 'POST_GENERIC_BATCH_CRUD_DETAILS_FAILURE';

export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
export const ADD_DEPARTMENT_SUCCESS = "ADD_DEPARTMENT_SUCCESS";
export const ADD_DEPARTMENT_FAILURE = "ADD_DEPARTMENT_FAILURE";

export const ADD_DESIGNATION = "ADD_DESIGNATION";
export const ADD_DESIGNATION_SUCCESS = "ADD_DESIGNATION_SUCCESS";
export const ADD_DESIGNATION_FAILURE = "ADD_DESIGNATION_FAILURE";

export const FETCH_DESIGNATION = "FETCH_DESIGNATION";
export const FETCH_DESIGNATION_SUCCESS = "FETCH_DESIGNATION_SUCCESS";
export const FETCH_DESIGNATION_FAILURE = "FETCH_DESIGNATION_FAILURE";

export const FETCH_DEPARTMENT = "FETCH_DEPARTMENT";
export const FETCH_DEPARTMENT_SUCCESS = "FETCH_DEPARTMENT_SUCCESS";
export const FETCH_DEPARTMENT_FAILURE = "FETCH_DEPARTMENT_FAILURE";

export const SET_CURRENT_COURSE_SECTION = "SET_CURRENT_COURSE_SECTION";
export const IS_DND_MODAL_OPEN = 'IS_DND_MODAL_OPEN';

export const ADD_STUDENT = "ADD_STUDENT";
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS";
export const ADD_STUDENT_FAILURE = "ADD_STUDENT_FAILURE";

export const FETCH_STUDENTS_LIST = "FETCH_STUDENTS_LIST";
export const FETCH_STUDENTS_LIST_SUCCESS = "FETCH_STUDENTS_LIST_SUCCESS";
export const FETCH_STUDENTS_LIST_FAILURE = "FETCH_STUDENTS_LIST_FAILURE";

export const ADD_FACULTY = "ADD_FACULTY";
export const ADD_FACULTY_SUCCESS = "ADD_FACULTY_SUCCESS";
export const ADD_FACULTY_FAILURE = "ADD_FACULTY_FAILURE";

export const FETCH_FACULTIES_LIST = "FETCH_FACULTIES_LIST";
export const FETCH_FACULTIES_LIST_SUCCESS = "FETCH_FACULTIES_LIST_SUCCESS";
export const FETCH_FACULTIES_LIST_FAILURE = "FETCH_FACULTIES_LIST_FAILURE";

export const FETCH_APPROVER_LIST = "FETCH_APPROVER_LIST";
export const FETCH_APPROVER_LIST_SUCCESS = "FETCH_APPROVER_LIST_SUCCESS";
export const FETCH_APPROVER_LIST_FAILURE = "FETCH_APPROVER_LIST_FAILURE";

export const FETCH_REFERER_LIST = "FETCH_REFERER_LIST";
export const FETCH_REFERER_LIST_SUCCESS = "FETCH_REFERER_LIST_SUCCESS";
export const FETCH_REFERER_LIST_FAILURE = "FETCH_REFERER_LIST_FAILURE";

export const SETTING_CURRENT_COURSE = "SETTING_CURRENT_COURSE"

export const FETCH_STUDENTS_DETAILS = "FETCH_STUDENTS_DETAILS";
export const FETCH_STUDENTS_DETAILS_SUCCESS = "FETCH_STUDENTS_DETAILS_SUCCESS";
export const FETCH_STUDENTS_DETAILS_FAILURE = "FETCH_STUDENTS_DETAILS_FAILURE";

export const SETTING_CURRENT_TASK_ITEM = "SETTING_CURRENT_TASK_ITEM";

export const FETCH_DASHBOARD_DETAILS = "FETCH_DASHBOARD_DETAILS";
export const FETCH_DASHBOARD_DETAILS_SUCCESS = "FETCH_DASHBOARD_DETAILS_SUCCESS";
export const FETCH_DASHBOARD_DETAILS_FAILURE = "FETCH_DASHBOARD_DETAILS_FAILURE";

export const SETTING_SELECTED_FACULTY_ID = "SETTING_SELECTED_FACULTY_ID";

export const EDIT_USER_REGISTRATION = 'EDIT_USER_REGISTRATION'

export const POST_RAISE_ANONYMOUS_COMPLAINT = "POST_RAISE_ANONYMOUS_COMPLAINT";
export const POST_RAISE_ANONYMOUS_COMPLAINT_SUCCESS = "POST_RAISE_ANONYMOUS_COMPLAINT_SUCCESS";
export const POST_RAISE_ANONYMOUS_COMPLAINT_FAILURE = "POST_RAISE_ANONYMOUS_COMPLAINT_FAILURE";

/**
 * Student
 */

export const FETCH_STUDENT_COURSES = "FETCH_STUDENT_COURSES";
export const FETCH_STUDENT_COURSES_SUCCESS = "FETCH_STUDENT_COURSES_SUCCESS";
export const FETCH_STUDENT_COURSES_FAILURE = "FETCH_STUDENT_COURSES_FAILURE";

export const FETCH_STUDENT_COURSE_SECTION = "FETCH_STUDENT_COURSE_SECTION";
export const FETCH_STUDENT_COURSE_SECTION_SUCCESS = "FETCH_STUDENT_COURSE_SECTION_SUCCESS";
export const FETCH_STUDENT_COURSE_SECTION_FAILURE = "FETCH_STUDENT_COURSE_SECTION_FAILURE";

export const FETCH_STUDENT_COURSE_TOPICS = "FETCH_STUDENT_COURSE_TOPICS";
export const FETCH_STUDENT_COURSE_TOPICS_SUCCESS = "FETCH_STUDENT_COURSE_TOPICS_SUCCESS";
export const FETCH_STUDENT_COURSE_TOPICS_FAILURE = "FETCH_STUDENT_COURSE_TOPICS_FAILURE";

export const FETCH_STUDENT_COURSE_TASKS = "FETCH_STUDENT_COURSE_TASKS";
export const FETCH_STUDENT_COURSE_TASKS_SUCCESS = "FETCH_STUDENT_COURSE_TASKS_SUCCESS";
export const FETCH_STUDENT_COURSE_TASKS_FAILURE = "FETCH_STUDENT_COURSE_TASKS_FAILURE";

export const FETCH_STUDENT_COURSE_TASKS_DETAILS = "FETCH_STUDENT_COURSE_TASKS_DETAILS";
export const FETCH_STUDENT_COURSE_TASKS_DETAILS_SUCCESS = "FETCH_STUDENT_COURSE_TASKS_DETAILS_SUCCESS";
export const FETCH_STUDENT_COURSE_TASKS_DETAILS_FAILURE = "FETCH_STUDENT_COURSE_TASKS_DETAILS_FAILURE";


export const FETCH_FACULTIES_DETAILS = "FETCH_FACULTIES_DETAILS";
export const FETCH_FACULTIES_DETAILS_SUCCESS = "FETCH_FACULTIES_DETAILS_SUCCESS";
export const FETCH_FACULTIES_DETAILS_FAILURE = "FETCH_FACULTIES_DETAILS_FAILURE";

export const SETTING_DEFAULT_COURSE = "SETTING_DEFAULT_COURSE"