export const GET_TASK_GROUPS_L = 'GET_TASK_GROUPS_L'
export const GET_TASK_GROUPS_L_SUCCESS = 'GET_TASK_GROUPS_L_SUCCESS'
export const GET_TASK_GROUPS_L_FAILURE = 'GET_TASK_GROUPS_L_FAILURE'



/* Task */
export const GET_TASKS = 'GET_TASKS';
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const GET_TASKS_FAILURE = 'GET_TASKS_FAILURE';


/* Task Itme */
export const SELECTED_TASK_ITEM = 'SELECTED_TASK_ITEM';

/**
 * Add Task Event
 */

export const ADD_TASK_EVENT = 'ADD_TASK_EVENT';
export const ADD_TASK_EVENT_SUCCESS = 'ADD_TASK_EVENT_SUCCESS';
export const ADD_TASK_EVENT_FAILURE = 'ADD_TASK_EVENT_FAILURE';

/**
 * get Task Event History
 */

export const GET_TASK_EVENT_HISTORY = 'GET_TASK_EVENT_HISTORY';
export const GET_TASK_EVENT_HISTORY_SUCCESS = 'GET_TASK_EVENT_HISTORY_SUCCESS';
export const GET_TASK_EVENT_HISTORY_FAILURE = 'GET_TASK_EVENT_HISTORY_FAILURE';

/**
 * get Sub Tasks
 */

export const GET_SUB_TASKS = 'GET_SUB_TASKS';
export const GET_SUB_TASKS_SUCCESS = 'GET_SUB_TASKS_SUCCESS';
export const GET_SUB_TASKS_FAILURE = 'GET_SUB_TASKS_FAILURE';


/**
 * get Task Events
 */

export const GET_TASK_EVENTS = 'GET_TASK_EVENTS';
export const GET_TASK_EVENTS_SUCCESS = 'GET_TASK_EVENTS_SUCCESS';
export const GET_TASK_EVENTS_FAILURE = 'GET_TASK_EVENTS_FAILURE';


/**
 * get reference task
 */

export const GET_REFERENCE_TASKS = 'GET_REFERENCE_TASKS';
export const GET_REFERENCE_TASKS_SUCCESS = 'GET_REFERENCE_TASKS_SUCCESS';
export const GET_REFERENCE_TASKS_FAILURE = 'GET_REFERENCE_TASKS_FAILURE';

/**
 * get Task User
 */

export const GET_TASK_USERS = 'GET_TASK_USERS';
export const GET_TASK_USERS_SUCCESS = 'GET_TASK_USERS_SUCCESS';
export const GET_TASK_USERS_FAILURE = 'GET_TASK_USERS_FAILURE';


/**
 * refresh task Events
 */

export const REFRESH_TASK_EVENTS = 'REFRESH_TASK_EVENTS';


/**
 * /**
 * get Task Events
 */

export const GET_TASK_EVENT_ATTACHMENTS = 'GET_TASK_EVENT_ATTACHMENTS';
export const GET_TASK_EVENT_ATTACHMENTS_SUCCESS = 'GET_TASK_EVENT_ATTACHMENTS_SUCCESS';
export const GET_TASK_EVENT_ATTACHMENTS_FAILURE = 'GET_TASK_EVENT_ATTACHMENTS_FAILURE';


export const SELECTED_TAB_POSITION = 'SELECTED_TAB_POSITION';

/* GET TASK DETAILS */

export const GET_TASK_DETAILS = 'GET_TASK_DETAILS';
export const GET_TASK_DETAILS_SUCCESS = 'GET_TASK_DETAILS_SUCCESS';
export const GET_TASK_DETAILS_FAILURE = 'GET_TASK_DETAILS_FAILURE';


/**
 * get Task group
 */


export const GET_SUB_TASK_GROUPS = 'GET_SUB_TASK_GROUPS';
export const GET_SUB_TASK_GROUPS_SUCCESS = 'GET_SUB_TASK_GROUPS_SUCCESS';
export const GET_SUB_TASK_GROUPS_FAILURE = 'GET_SUB_TASK_GROUPS_FAILURE';

// getAssignedTask
export const GET_ASSIGNED_TASK = 'GET_ASSIGNED_TASK';
export const GET_ASSIGNED_TASK_SUCCESS = 'GET_ASSIGNED_TASK_SUCCESS';
export const GET_ASSIGNED_TASK_FAILURE = 'GET_ASSIGNED_TASK_FAILURE';

export const TASK_DEFAULT_PARAMS = 'TASK_DEFAULT_PARAMS'


export const ASSIGNED_DEPARTMENT='ASSIGNED_DEPARTMENT'
export const ASSIGNED_DESIGNATION='ASSIGNED_DESIGNATION'
export const ASSIGNED_EMPLOYEE='ASSIGNED_EMPLOYEE'


export const CREATED_DEPARTMENT='CREATED_DEPARTMENT'
export const CREATED_DESIGNATION='CREATED_DESIGNATION'
export const CREATED_EMPLOYEE='CREATED_EMPLOYEE'

export const GET_TIMELINE_BREAKDOWN='GET_TIMELINE_BREAKDOWN'
export const GET_TIMELINE_BREAKDOWN_SUCCESS='GET_TIMELINE_BREAKDOWN_SUCCESS'
export const GET_TIMELINE_BREAKDOWN_FAILURE='GET_TIMELINE_BREAKDOWN_FAILURE'

export const SELECTED_TASK_ID='SELECTED_TASK_ID'

export const SELECTED_REFERENCE='SELECTED_REFERENCE'

