export const RAISE_NEW_TICKET = 'RAISE_NEW_TICKET';
export const RAISE_NEW_TICKET_SUCCESS = 'RAISE_NEW_TICKET_SUCCESS';
export const RAISE_NEW_TICKET_FAILURE = 'RAISE_NEW_TICKET_FAILURE';

export const GET_TICKETS = 'GET_TICKETS';
export const GET_TICKETS_SUCCESS = 'GET_TICKETS_SUCCESS';
export const GET_TICKETS_FAILURE = 'GET_TICKETS_FAILURE';

export const GET_TICKET_TAGS = 'GET_TICKET_TAGS';
export const GET_TICKET_TAGS_SUCCESS = 'GET_TICKET_TAGS_SUCCESS';
export const GET_TICKET_TAGS_FAILURE = 'GET_TICKET_TAGS_FAILURE';

export const ADD_TICKET_EVENT = 'ADD_TICKET_EVENT';
export const ADD_TICKET_EVENT_SUCCESS = 'ADD_TICKET_EVENT_SUCCESS';
export const ADD_TICKET_EVENT_FAILURE = 'ADD_TICKET_EVENT_FAILURE';

export const GET_TICKET_EVENTS = 'GET_TICKETS_EVENT';
export const GET_TICKET_EVENTS_SUCCESS = 'GET_TICKETS_EVENT_SUCCESS';
export const GET_TICKET_EVENTS_FAILURE = 'GET_TICKETS_EVENT_FAILURE';

export const GET_REFERENCE_TICKETS = 'GET_REFERENCE_TICKETS';
export const GET_REFERENCE_TICKETS_SUCCESS = 'GET_REFERENCE_TICKETS_SUCCESS';
export const GET_REFERENCE_TICKETS_FAILURE = 'GET_REFERENCE_TICKETS_FAILURE';


export const GET_TICKET_USERS = 'GET_TICKET_USERS';
export const GET_TICKET_USERS_SUCCESS = 'GET_TICKET_USERS_SUCCESS';
export const GET_TICKET_USERS_FAILURE = 'GET_TICKET_USERS_FAILURE';


export const SELECTED_TICKET_ITEM = 'SELECTED_TICKET_ITEM';
export const SET_REFERENCE_SELECTED_TICKETS = 'SET_REFERENCE_SELECTED_TICKETS';
export const REFERENCE_TICKET_DETAILS = "REFERENCE_TICKET_DETAILS";

/**
 * refresh task Events
 */ 

export const REFRESH_TICKET_EVENTS = 'REFRESH_TICKET_EVENTS';

 
export const SELECTED_TICKET_TAB_POSITION = 'SELECTED_TICKET_TAB_POSITION';

 /**
 * Get Ticket Event History
 */

export const GET_TICKET_EVENT_HISTORY = 'GET_TICKET_EVENT_HISTORY';
export const GET_TICKET_EVENT_HISTORY_SUCCESS = 'GET_TICKET_EVENT_HISTORY_SUCCESS';
export const GET_TICKET_EVENT_HISTORY_FAILURE = 'GET_TICKET_EVENT_HISTORY_FAILURE';


/* GET TASK DETAILS */

export const GET_TICKET_DETAILS = 'GET_TICKET_DETAILS';
export const GET_TICKET_DETAILS_SUCCESS = 'GET_TICKET_DETAILS_SUCCESS';
export const GET_TICKET_DETAILS_FAILURE = 'GET_TICKET_DETAILS_FAILURE';

/**
 * /**
 * get Ticket Events
 */

 export const GET_TICKET_EVENT_ATTACHMENTS = 'GET_TICKET_EVENT_ATTACHMENTS';
 export const GET_TICKET_EVENT_ATTACHMENTS_SUCCESS = 'GET_TICKET_EVENT_ATTACHMENTS_SUCCESS';
 export const GET_TICKET_EVENT_ATTACHMENTS_FAILURE = 'GET_TICKET_EVENT_ATTACHMENTS_FAILURE';

 export const GET_TICKET_PARAMS='GET_TICKET_PARAMS';




