
export interface UserCompanyStateProp {

  designations: any,
  departments: any,
  designationCurrentPages: any,
  designationNumOfPages: any,
  departmentsCurrentPages: any,
  departmentsNumOfPages: any,
  brandSector: any,
  ticketTag: any,
  brandSectorCurrentPages: any,
  brandSectorNumOfPages: any,
  ticketTagCurrentPages: any,
  ticketTagNumOfPages: any,
  taskGroups: any,
  getTaskGroupCurrentPages: any,
  taskGroupDetails: any,
  taskGroupCurrentPages: any,
  taskGroupNumOfPages: any,
  addTaskGroup: any,
  loading?: boolean;
  error?: string;
  associatedCompanies: any,
  associatedCompaniesNumOfPages: any,
  associatedCompaniesCurrentPages: any,
  addEmployeeDetails: any,
  updateEmployeeProfile: any,
  employees: any,
  employeesCurrentPages: any,
  employeesNumOfPages: any,
  response: any,
  registerAdminResponse: any,
  associatedCompaniesL: any,
  dashboardDetails: any,
  selectedCompany: any,
  employeesl: any,
  employeeAddTime: any,
  employeeTimeline: any,
  selectedEmployee: any,

  employeeTimelineCurrentPages: any,
  employeeTimelineNumOfPages: any,
  employeeslCurrentPages: any,
  employeeslNumOfPages: any,
  events: any,
  eventsCurrentPages: number
  videoConference: any,
  scheduledListData: any,
  userToken: any,
  associatedCompany: any,
  updateAssociatedCompany: any,
  refreshUserCompany: boolean,
  groupEmployees: any,
  groupMessages: any,
  addGroupMessages: any,
  refreshGroupEvents: boolean,
  selectedGroup: any,
  getSubGroups: any,
  selectedGroupChat: any,
  chatGroups: any,
  selectedTaskGroupCode: any,
  employeesDetails: any,
  refreshGroupChat: any,
  timeStatus: any,
  enableRequestDataList: any,
  enableRequest: any,
  selectedPrivateUser: any,
  settingVcDetails: any,
  vcNotificationData: any
  employeeListData: any
  oneToOneChat: any
  oneToOneVcNoti: any,
  chatEmployees: any,
  chatEmployeeListCurrentPages: any,
  chatEmployeeListNumOfPages: any,
  refreshChatMessage: any,
  chatMessageCurrentPages: number,
  chatMessages: any,
  groupMessageCurrentPage: number;
  refreshPrivateChat?: boolean;
  userDataList?:any;
  companiesServiceProduct:any,
  companiesServiceProductCurrentPages:any,
  companiesServiceProductNumOfPages:any,
  addProductServiceList:any,
  fetchProductCategoryData:any,
  addProductCategoryData:any,
  companiesBrandService:any,
  companiesBrandServiceCurrentPages:any,
  companiesBrandServiceNumOfPages:any,
  addBrandServiceData:any,
  fetchServiceCategoryData:any,
  addServiceCategoryData:any

}