
export interface UserCompanyStateProp {

    designations: any,
    departments: any,
    designationCurrentPages: any,
    designationNumOfPages: any,
    departmentsCurrentPages: any,
    departmentsNumOfPages: any,
    brandSector: any,
    ticketTag: any,
    brandSectorCurrentPages: any,
    brandSectorNumOfPages: any,
    ticketTagCurrentPages: any,
    ticketTagNumOfPages: any,
    taskGroups: any,
    getTaskGroupCurrentPages: any,
    taskGroupDetails: any,
    taskGroupCurrentPages: any,
    taskGroupNumOfPages: any,
    addTaskGroup: any,
    loading?: boolean;
    error?: string;
    associatedCompanies: any,
    associatedCompaniesNumOfPages: any,
    associatedCompaniesCurrentPages: any,
    addEmployeeDetails: any,
    updateEmployeeProfile: any,
    employees: any,
    response: any,
    registerAdminResponse: any,
    associatedCompaniesL: any,
    dashboardDetails: any,
    selectedCompany: any,
    employeesl:any,
    employeeAddTime:any,
    employeeTimeline:any,
    selectedEmployee:any,
    employeeTimelineCurrentPages:any,
    employeeTimelineNumOfPages:any,
    employeeslCurrentPages:any,
    employeeslNumOfPages:any,
    events:any,
    eventsCurrentPages:number
    videoConference:any,
    scheduledListData:any,
    userToken:any
}